name: OpenWrt Netgear R7800

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: "0 0/12 * * 2-6"

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  check:
    outputs:
      latest: ${{ steps.latest.outputs.is_latest }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
      - name: Set Environment Variable
        run: |
          OPENWRT_VERSION=`./latest-imagebuilder-version.sh ath79 tiny`
          echo "OPENWRT_VERSION=${OPENWRT_VERSION}" >> $GITHUB_ENV
      - id: latest
        name: Check Published Version
        run: |
          PUBLISHED_VERSION=`curl 'https://downloads.hackinggate.com' | grep 'r7800' | grep -E -o ${OPENWRT_VERSION} | tail -1`
          echo "${OPENWRT_VERSION} is latest"
          if [[ "$OPENWRT_VERSION" == "$PUBLISHED_VERSION" ]]; then
            echo "${OPENWRT_VERSION} is published for r7800"
            echo "::set-output name=is_latest::true"
          else
            echo "${OPENWRT_VERSION} is NOT published for r7800"
          fi
  build:
    needs: check
    if: ${{ needs.check.outputs.latest != 'true' || github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
      - name: Set Environment Variable
        run: |
          OPENWRT_VERSION=`./latest-imagebuilder-version.sh ath79 tiny`
          echo "OPENWRT_VERSION=${OPENWRT_VERSION}" >> $GITHUB_ENV
      - name: Prerequisites
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev libncursesw5-dev \
          zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python \
          jq tree
      - name: Build R7800 with imagebuilder
        run: |
          OPENWRT_VERSION=${{ env.OPENWRT_VERSION }}
          ./r7800-openwrt-imagebuilder-build.sh
      - name: Checkout gh-pages
        run : |
          git config --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch origin gh-pages
          git checkout gh-pages
      - name: Override Files
        run: |
          OPENWRT_VERSION=${{ env.OPENWRT_VERSION }}
          IMAGE_PREFIX=`cat openwrt-imagebuilder-${OPENWRT_VERSION}-ipq806x-generic.Linux-x86_64/bin/targets/ipq806x/generic/profiles.json | jq '.["profiles"]' | jq 'map(.)' | jq -r '.[0]["image_prefix"]'`
          rm -rf ${IMAGE_PREFIX}
          mv openwrt-imagebuilder-${OPENWRT_VERSION}-ipq806x-generic.Linux-x86_64/bin/targets/ipq806x/generic ${IMAGE_PREFIX}
          rm -rf openwrt-imagebuilder-*
      - name: Generate gh-pages
        run: |
          git checkout - -- generate-page.sh
          ./generate-page.sh
          rm generate-page.sh
      - name: Tree
        run: | 
          sudo apt install tree
          tree
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: .
          clean: true
          dry-run: ${{ github.event_name == 'pull_request' }}
