name: OpenWrt 21.02 TL-703N 16m (custombuild)

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: "21 2/12 * * 2-6"

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  check:
    outputs:
      latest: ${{ steps.latest.outputs.is_latest }}
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variable
        run: |
          OPENWRT_TAG=`git ls-remote https://github.com/openwrt/openwrt | grep -E -o 'v21.02\.[0-9]+' | tail -1`
          OPENWRT_VERSION=`echo ${OPENWRT_TAG} | grep -E -o '[0-9]+\.[0-9]+\.[0-9]+'`
          echo "OPENWRT_TAG=${OPENWRT_TAG}" >> $GITHUB_ENV
          echo "OPENWRT_VERSION=${OPENWRT_VERSION}" >> $GITHUB_ENV
      - id: latest
        name: Check Published Version
        run: |
          PUBLISHED_VERSION=`curl 'https://downloads.hackinggate.com' | grep 'tl-wr703n' | grep -E -o '21.02\.[0-9]+' | sort -V | tail -1 || echo 0.0.0`
          if [[ "$OPENWRT_VERSION" == "$PUBLISHED_VERSION" ]]; then
            echo "::set-output name=is_latest::true"
          fi
  build:
    needs: check
    if: ${{ needs.check.outputs.latest != 'true' || github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Environment Variable
        run: |
          OPENWRT_TAG=`git ls-remote https://github.com/openwrt/openwrt | grep -E -o 'v21.02\.[0-9]+' | tail -1`
          OPENWRT_VERSION=`echo ${OPENWRT_TAG} | grep -E -o '[0-9]+\.[0-9]+\.[0-9]+'`
          echo "OPENWRT_TAG=${OPENWRT_TAG}" >> $GITHUB_ENV
          echo "OPENWRT_VERSION=${OPENWRT_VERSION}" >> $GITHUB_ENV
      - name: Prepare Custom Build WR703N
        run: |
          OPENWRT_TAG=${{ env.OPENWRT_TAG }}
          OPENWRT_VERSION=${{ env.OPENWRT_VERSION }}
          ./wr703n-21.02-openwrt-custom-build.sh
      - name: Make
        run: |
          cd openwrt
          make -j4 V=s
      - name: Tree
        run: |
          sudo apt install tree
          tree openwrt/bin/
      - name: Checkout gh-pages
        run : |
          git config --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch origin gh-pages
          git checkout gh-pages
      - name: Override Files
        run: |
          OPENWRT_VERSION=${{ env.OPENWRT_VERSION }}
          rm -rf openwrt-${OPENWRT_VERSION}-tl-wr703n-v1-16m
          mkdir openwrt-${OPENWRT_VERSION}-tl-wr703n-v1-16m
          find openwrt/bin/targets/ath79/generic/ -name 'openwrt-'${OPENWRT_VERSION}'-*-tl-wr703n-v1*' -exec mv {} openwrt-${OPENWRT_VERSION}-tl-wr703n-v1-16m \;
          mv openwrt/bin/targets/ath79/generic/profiles.json openwrt-${OPENWRT_VERSION}-tl-wr703n-v1-16m
          rm -rf openwrt
      - name: Generate gh-pages
        run: |
          git checkout - -- generate-page.sh
          ./generate-page.sh
          rm generate-page.sh
      - name: Tree
        run: | 
          sudo apt install tree
          tree
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: .
          clean: true
          dry-run: ${{ github.event_name == 'pull_request' }}
